openapi: 3.0.0
info:
  title: Portfolio
  description: projects API
  version: 0.1.9

servers:
  - url: https://portfolio-api-production-71be.up.railway.app/api
    description: production server
  - url: http://localhost:3000/api
    description: local server
paths:
  /projects:
    post:
      tags:
        - Projects
      requestBody:
        description: add project
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string;
                description:
                  type: string;
                url:
                  type: string;
                poster:
                  type: string
                  format: binary
                tag:
                  type: string;
                tools:
                  type: array
                  items:
                    type: string
                  example: ["html", "css", "js"]
      responses:
        "200":
          description: project created
    get:
      tags:
        - Projects
      responses:
        "200":
          description: Successfully fetched
  /projects/{id}:
    get:
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      tags:
        - Projects
      responses:
        "200":
          description: Successfully fetched
  /screenshots:
    post:
      tags:
        - Projects
      requestBody:
        description: add screenshot
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                projectId:
                  type: string;
                screen:
                  type: string
                  format: binary
      responses:
        "200":
          description: screenshot saved
  /message:
    post:
      tags:
        - Message
      requestBody:
        description: send mail
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                text:
                  type: string
      responses:
        "200"
          description: mail send
